import { trackingNotice, EVENT_LABEL, ENGINE, VERDICT_LABEL, VIEW_LABEL, nextSteps, paceText, summarize, flights, type Report } from "./racewalk";
import { measurementNotes } from "./measurement-math";
export const escapeHtml=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export function download(content:Blob|string,name:string,type="application/json"){
 const url=URL.createObjectURL(typeof content==="string"?new Blob([content],{type}):content);const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function csvReport(r:Report){
 const cell=(v:unknown)=>{let s=String(v??"");if(/^[=+\-@\t\r]/.test(s)&&typeof v!=="number")s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};
 const rows:unknown[][]=[["引擎",r.engine],["目標追蹤",trackingNotice(r)],["選手",r.settings.athlete],["日期",r.settings.date],["視角",VIEW_LABEL[r.settings.view]],["時間基準",r.settings.timingVerified?"已由使用者確認":"未確認；不提供實際毫秒／步頻"],...measurementNotes(r.settings).map(note=>["量測條件",note]),["原片SHA256",r.file.sha256],["影片時間秒","左右","事件","狀態","來源","備註"]];
 for(const e of r.events)rows.push([e.t,e.side,EVENT_LABEL[e.kind],e.status,e.origin,e.note]);
 return "\uFEFF"+rows.map(r=>r.map(cell).join(",")).join("\r\n");
}
export function htmlReport(r:Report,png?:string){
 const a=summarize(r),e=escapeHtml,v=(x:number|null)=>x===null?"N/A":x.toFixed(1);
 return `<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(r.settings.athlete)} 競走影片分析 ${e(r.settings.date)}</title><style>body{font-family:Arial,"Microsoft JhengHei",sans-serif;color:#182538;max-width:960px;margin:40px auto;padding:0 24px;line-height:1.6}h1{font-size:26px}h2{font-size:20px;margin-top:30px}table{border-collapse:collapse;width:100%;margin:16px 0}td,th{border:1px solid #dce2ea;padding:9px;text-align:left}th{background:#eff3fa}small{color:#53647a}img{max-width:100%}.warn{color:#a13e0c}@media print{body{margin:0;font-size:11pt}tr{break-inside:avoid}h2{break-after:avoid}} </style><h1>${e(r.settings.athlete)} 競走影片分析</h1><p>${e(r.settings.date)} · ${e(VIEW_LABEL[r.settings.view])} · 配速 ${e(paceText(r.settings.pace))}／公里</p><small>引擎 ${e(r.engine)} · 版本 ${r.version} · ${r.complete?"區間分析完成":"分析未完成"} · ${r.settings.timingVerified?"時間基準經使用者確認":"時間基準未確認"}</small><p class="warn">本報告為訓練篩查。角度、接觸候選與研究門檻不能取代正式裁判或醫療評估。</p><p class="warn">${e(trackingNotice(r))}</p><h2>正常速度人工複查</h2><table><tr><th>接觸</th><th>左膝</th><th>右膝</th></tr><tr><td>${e(VERDICT_LABEL[r.judge.contact])}</td><td>${e(VERDICT_LABEL[r.judge.left])}</td><td>${e(VERDICT_LABEL[r.judge.right])}</td></tr></table><h2>量測條件與誤差</h2>${measurementNotes(r.settings).map(note=>`<p>${e(note)}</p>`).join("")}<h2>已複查的量測窗口</h2><p>骨架幀覆蓋率 ${v(a.coverage)}%（可能含局部缺值） · 已確認左／右窗口 ${a.leftCount}／${a.rightCount} · 步頻 ${v(a.cadence)}步／分</p><p>窗口最低膝角的中位數：左 ${v(a.leftMin)}°，右 ${v(a.rightMin)}°。非近鏡頭側不提供精確角度。</p>${png?`<h2>選取的關鍵幀</h2><img alt="原片加量測點線與參考線" src="${png}"><p>藍色左側、橘色右側；虛線為伸膝參考軸，不是矯正後的實際動作。</p>`:""}<h2>下一次重點</h2>${nextSteps(r).map(s=>`<h3>${e(s.title)}</h3><p>${e(s.reason)} ${e(s.action)}</p>`).join("")}<h2>事件與證據</h2><table><tr><th>影片秒數</th><th>側</th><th>事件</th><th>狀態</th><th>備註</th></tr>${r.events.map(ev=>`<tr><td>${ev.t.toFixed(3)}</td><td>${e(ev.side)}</td><td>${e(EVENT_LABEL[ev.kind])}</td><td>${e(ev.status)}</td><td>${e(ev.note)}</td></tr>`).join("")}</table><h2>接觸時間差</h2>${flights(r).length?flights(r).map(f=>`<p>${e(f.direction)}：${f.ms.toFixed(1)} ms，取樣不確定範圍約 ±${f.uncertainty.toFixed(1)} ms。</p>`).join(""):"<p>N/A：尚無足夠且經確認的交替事件與時間基準。</p>"}<h2>教練備註</h2><p>${e(r.notes).replace(/\n/g,"<br>")}</p><small>原片：${e(r.file.name)} · SHA256：${e(r.file.sha256||"未取得")}<br>複查者：${e(r.settings.reviewer||"尚未填寫")}</small><p><a href="https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker">MediaPipe Pose</a> · <a href="https://worldathletics.org/news/series/race-walking-technique-rules-straight-leg">World Athletics伸膝說明</a></p></html>`;
}
