"use client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect } from "@/components/ui/native-select";
import { Switch } from "@/components/ui/switch";
import { Camera, ChevronRight, Download, FileJson, FileText, Footprints, Printer, Trash2 } from "lucide-react";
import { trackingNotice, VIEW_LABEL, VERDICT_LABEL, SPEED_LABEL, EVENT_LABEL, summarize, nextSteps, flights, kneeWindows, paceText, parsePace, timeText, type Settings, type Report, type WalkEvent, type Verdict } from "@/lib/racewalk";
import type { ReactNode } from "react";
import { measurementNotes } from "@/lib/measurement-math";

export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function SettingsPanel({s,patch,locked,hasFrames}:{s:Settings;patch:(p:Partial<Settings>)=>void;locked:boolean;hasFrames:boolean}){
 return <section className="card settings-card"><div className="section-head"><h2>本次拍攝</h2><span className="step-tag">01</span></div><fieldset disabled={locked}>
 <div className="form-grid"><Field label="選手"><Input value={s.athlete} maxLength={80} onChange={e=>patch({athlete:e.target.value})}/></Field><Field label="日期"><Input type="date" value={s.date} onChange={e=>patch({date:e.target.value})}/></Field></div>
 <Field label="拍攝視角"><NativeSelect value={s.view} disabled={hasFrames} onChange={e=>patch({view:e.target.value as Settings["view"]})}>{Object.entries(VIEW_LABEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</NativeSelect></Field>
 <div className="form-grid"><Field label="行進方向"><NativeSelect disabled={hasFrames} value={s.direction} onChange={e=>patch({direction:e.target.value as Settings["direction"]})}><option value="right">畫面左 → 右</option><option value="left">畫面右 → 左</option></NativeSelect></Field><Field label="速度組別"><NativeSelect value={s.speed} onChange={e=>patch({speed:e.target.value as Settings["speed"]})}>{Object.entries(SPEED_LABEL).map(([v,l])=><option value={v} key={v}>{l}</option>)}</NativeSelect></Field></div>
 <Field label="實際配速（分:秒／公里）" hint="留空即未記錄，不以目標配速代替實測。"><Input key={`${s.pace}-${s.date}`} placeholder="例如 6:19" defaultValue={s.pace===null?"":paceText(s.pace,true)} onBlur={e=>{const v=parsePace(e.target.value);e.target.setCustomValidity(e.target.value&&!v?"請填分:秒，例如6:19":"");e.target.reportValidity();if(!e.target.value||v)patch({pace:v});}}/></Field>
 <Field label="今天的髖部／步態狀況"><NativeSelect value={s.pain} onChange={e=>patch({pain:e.target.value as Settings["pain"]})}><option value="unknown">尚未確認</option><option value="none">無不適、無跛行</option><option value="yes">有不適、跛行或疼痛增加</option></NativeSelect></Field>
 {s.pain==="yes"&&<div className="notice stop"><strong>STOP SPEED SESSION</strong><p>停止速度訓練，先由教練／運動醫療人員評估；仍可整理既有影片。</p></div>}
 <details><summary>時間與取樣設定</summary><div className="form-grid"><Field label="原始拍攝 fps"><NativeSelect value={s.fps} disabled={hasFrames} onChange={e=>patch({fps:Number(e.target.value)})}>{[24,25,30,50,60,120,240].map(v=><option key={v} value={v}>{v} fps</option>)}</NativeSelect></Field><Field label="每實際秒取樣"><NativeSelect value={s.sampleFps} disabled={hasFrames} onChange={e=>patch({sampleFps:Number(e.target.value)})}>{[15,30,60,120,240].map(v=><option key={v} value={v}>{v} 格</option>)}</NativeSelect></Field></div>
 <Field label="原片慢放倍率" hint="一般原片選1；拍攝1秒、檔案播放4秒則選4。若不清楚，勿勾選時間已確認。"><NativeSelect value={s.slow} disabled={hasFrames} onChange={e=>patch({slow:Number(e.target.value),timingVerified:false})}>{[1,2,4,8,16].map(v=><option key={v} value={v}>{v===1?"1・一般速度":`${v}・已慢放${v}倍`}</option>)}</NativeSelect></Field>
 <label className="switch-field"><Switch checked={s.timingVerified} onCheckedChange={v=>patch({timingVerified:v})}/><span>已確認原始 fps 與慢放倍率</span></label><p className="meta">未確認時不計算實際步頻或毫秒。變動幀率與手機補幀仍需原始檔人工核對。</p></details>
 {hasFrames&&<p className="meta">鏡位和時間取樣設定已鎖定；需要更改時請清除分析後重算。</p>}
 </fieldset></section>;
}
export function JudgePanel({r,change,disabled}:{r:Report;change:(key:keyof Report["judge"],v:Verdict)=>void;disabled:boolean}){
 return <section className="judge-panel"><div className="section-head"><h3>正常速度人工複查</h3><span className="pill">Judge View</span></div><p className="helper">先以還原的正常速度觀看原片，再填觀察。慢動作毫秒與膝角不會自動轉成此處結論。</p><div className="judge-grid">{([["contact","雙腳接觸"],["left","左膝伸直"],["right","右膝伸直"]] as const).map(([key,label])=><Field key={key} label={label}><NativeSelect value={r.judge[key]} disabled={disabled} className={`verdict-${r.judge[key]}`} onChange={e=>change(key,e.target.value as Verdict)}>{Object.entries(VERDICT_LABEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</NativeSelect></Field>)}</div>{!r.settings.timingVerified&&<p className="meta">請先確認時間設定，才能填入正常速度的明確觀察。</p>}</section>;
}
export function EventList({r,onSeek,onChange,onDelete,disabled}:{r:Report;onSeek:(t:number)=>void;onChange:(id:string,p:Partial<WalkEvent>)=>void;onDelete:(id:string)=>void;disabled:boolean}){
 const all=r.events.filter(e=>e.status!=="rejected").sort((a,b)=>a.t-b.t);
 return <section className="card events-card"><div className="section-head"><h2>關鍵事件複查</h2><span className="pill">{all.length} 個</span></div><p className="helper">黃色是模型候選。點時間看原片，修正時間後再確認；只有已確認事件進入窗口摘要。</p>
 {!all.length?<div className="empty-inline"><Footprints/><p>分析後顯示候選，也可從目前畫面手動新增事件。</p></div>:<div className="event-list">{all.map(e=><article className={`event-row event-${e.status}`} key={e.id}><div className="event-top"><button className="time-link" disabled={disabled} onClick={()=>onSeek(e.t)}>{timeText(e.t)}</button><span className={`side-label side-${e.side}`}>{e.side==="L"?"左":"右"}</span><strong>{EVENT_LABEL[e.kind]}</strong><span className="meta">{e.origin==="auto"?"AI候選":"人工標記"}</span></div><p>{e.note}</p><div className="event-controls"><Input aria-label={`${EVENT_LABEL[e.kind]}時間（影片秒）`} disabled={disabled} type="number" step={.001} min={0} max={r.file.duration} value={e.t} onChange={v=>{const n=Number(v.target.value);if(Number.isFinite(n)&&n>=0&&n<=r.file.duration)onChange(e.id,{t:n,status:"pending"});}}/><Button disabled={disabled} size="sm" variant={e.status==="confirmed"?"secondary":"outline"} onClick={()=>onChange(e.id,{status:e.status==="confirmed"?"pending":"confirmed"})}>{e.status==="confirmed"?"已確認 ✓":"確認事件"}</Button><Button disabled={disabled} size="sm" variant="ghost" onClick={()=>onChange(e.id,{status:"rejected"})}>排除</Button>{e.origin==="manual"&&<Button disabled={disabled} size="icon-sm" aria-label="刪除此人工事件" variant="ghost" onClick={()=>onDelete(e.id)}><Trash2/></Button>}</div></article>)}</div>}
 {r.events.some(e=>e.status==="rejected")&&<details><summary>已排除 {r.events.filter(e=>e.status==="rejected").length} 個事件</summary>{r.events.filter(e=>e.status==="rejected").map(e=><div key={e.id} className="row-between"><span>{timeText(e.t)} {e.side} {EVENT_LABEL[e.kind]}</span><Button size="sm" variant="ghost" disabled={disabled} onClick={()=>onChange(e.id,{status:"pending"})}>恢復</Button></div>)}</details>}
 </section>;
}
export type HistoryRow={id:string;athlete:string;session_date:string;view:Settings["view"];speed:Settings["speed"];pace:number|null;file_name:string;summary:ReturnType<typeof summarize>;version:number;archived:boolean;updated_at:string};
export function HistoryPanel({rows,loading,onRefresh,onOpen,onDelete}:{rows:HistoryRow[];loading:boolean;onRefresh:()=>void;onOpen:(id:string)=>void;onDelete:(id:string)=>void}){
 return <section className="card history-card"><div className="section-head"><div><h2>每一次，都留下比較的依據</h2><p className="helper">分開保留鏡位、速度、症狀與人工複查結果。原片是否備份會獨立標示。</p></div><Button variant="outline" onClick={onRefresh} disabled={loading}>{loading?"讀取中…":"重新整理"}</Button></div>
 {!rows.length?<div className="empty-large"><Footprints size={38}/><h3>{loading?"正在讀取訓練紀錄":"從第一支影片建立個人基準"}</h3><p>完成分析並儲存後，紀錄會出現在這裡。</p></div>:<div className="table-scroll"><table><thead><tr><th>日期／選手</th><th>拍攝條件</th><th>已確認窗口 L／R</th><th>膝角摘要 L／R</th><th>原片</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.session_date}</strong><small>{row.athlete}</small></td><td>{VIEW_LABEL[row.view]}<small>{SPEED_LABEL[row.speed]} · {paceText(row.pace)}/km</small></td><td>{row.summary.leftCount}／{row.summary.rightCount}</td><td>{row.summary.leftMin?.toFixed(1)??"—"}°／{row.summary.rightMin?.toFixed(1)??"—"}°</td><td><span className="pill">{row.archived?"已備份":"保留在裝置"}</span></td><td><div className="button-row"><Button size="sm" variant="outline" onClick={()=>onOpen(row.id)}>開啟<ChevronRight/></Button><Button size="icon-sm" aria-label={`刪除${row.session_date}紀錄`} variant="ghost" onClick={()=>onDelete(row.id)}><Trash2/></Button></div></td></tr>)}</tbody></table></div>}
 <div className="notice"><strong>如何比較進步？</strong><p>先比同一選手、同一鏡位、相近實測配速的紀錄，再看窗口數與原片。角度摘要是「每個已確認窗口最低角度的中位數」，不能單靠數字判定進步；未建立校準前不產生總分或犯規率。</p></div></section>;
}
export function ReportPanel({r,png,notes,reviewer,onExport,onPrint}:{r:Report;png:string|null;notes:(v:string)=>void;reviewer:(v:string)=>void;onExport:(type:"html"|"csv"|"json")=>void;onPrint:()=>void}){
 const a=summarize(r),steps=nextSteps(r),windows=kneeWindows(r),flight=flights(r),n=(v:number|null)=>v===null?"—":v.toFixed(1);
 return <article className="card report-card"><div className="report-title"><div><span className="eyebrow">RACE WALK VIDEO CHECK REPORT</span><h2>{r.settings.athlete} · 動作分析報告</h2><p>{r.settings.date} ／ {VIEW_LABEL[r.settings.view]} ／ {SPEED_LABEL[r.settings.speed]} ／ {paceText(r.settings.pace)}/km</p></div><span className="pill">{r.complete?"區間分析完成":"尚未完成分析"}</span></div>
 <div className="button-row no-print"><Button variant="outline" onClick={()=>onExport("html")}><FileText/>HTML報告</Button><Button variant="outline" onClick={()=>onExport("csv")}><Download/>事件CSV</Button><Button variant="outline" onClick={()=>onExport("json")}><FileJson/>完整JSON</Button><Button variant="outline" onClick={onPrint}><Printer/>列印／PDF</Button></div>
 <div className="tracking-status tracking-alert"><strong>選手追蹤紀錄</strong><span>{trackingNotice(r)}</span></div>
 <div className="report-section"><h3>量測條件與誤差</h3>{measurementNotes(r.settings).map(note=><p className="helper" key={note}>{note}</p>)}</div>
 <div className="report-section"><h3>Judge View · 正常速度人工觀察</h3><div className="metric-grid">{([["contact","接觸"],["left","左膝"],["right","右膝"]] as const).map(([k,l])=><div className="metric" key={k}><span>{l}</span><strong className={`verdict-${r.judge[k]}`}>{VERDICT_LABEL[r.judge[k]]}</strong></div>)}</div></div>
 <div className="report-section"><h3>Biomechanics · 已複查量測</h3><div className="metric-grid"><div className="metric"><span>左／右膝角摘要</span><strong>{n(a.leftMin)}° / {n(a.rightMin)}°</strong><small>窗口最低角度的中位數</small></div><div className="metric"><span>已確認窗口 L／R</span><strong>{a.leftCount} / {a.rightCount}</strong><small>IC 到 Vertical</small></div><div className="metric"><span>步頻</span><strong>{n(a.cadence)} <small>步／分</small></strong><small>需要連續交替接地與時間確認</small></div></div><p className="helper">已取樣 {a.frames} 格，骨架幀覆蓋 {n(a.coverage)}%（可能含局部缺值）；{r.frames.filter(f=>f.manual).length} 格含人工標點。點位信心不足、遠側遮擋或非側面膝角顯示「—」。</p>
 {windows.length>0&&<div className="table-scroll"><table><thead><tr><th>腳側</th><th>已確認窗口</th><th>最低二維膝角</th><th>有效格／總格</th></tr></thead><tbody>{windows.map((w,i)=><tr key={i}><td>{w.side}</td><td>{timeText(w.start)}—{timeText(w.end)}</td><td>{w.min.toFixed(1)}°</td><td>{w.valid}／{w.total}</td></tr>)}</tbody></table></div>}
 {flight.length>0&&<div className="notice"><strong>經複查事件的可能離地間隔</strong>{flight.map((f,i)=><p key={i}>{f.direction} · {f.ms.toFixed(1)} ms（取樣不確定範圍約 ±{f.uncertainty.toFixed(1)} ms）</p>)}<small>不確定範圍跨過0時，資料不足以確定真的有離地間隔。</small></div>}</div>
 {png&&<figure className="report-figure"><img src={png} alt="選取的競走原片關鍵幀與骨架量測"/><figcaption>目前選取的畫面；虛線是伸膝參考軸，不是已矯正的實際動作。</figcaption></figure>}
 <div className="report-section"><h3>下一堂課，先處理這些事</h3><div className="next-steps">{steps.map((s,i)=><div key={s.title} className={r.settings.pain==="yes"?"next-item stop":"next-item"}><span className="step-number">0{i+1}</span><div><h4>{s.title}</h4><p>{s.reason}</p><strong>{s.action}</strong></div></div>)}</div><p className="helper">本版依已確認證據提出重拍與技術觀察建議；髖伸展不足、肌力不足等原因，不能由單支二維影片直接確診。</p></div>
 <div className="form-grid no-print"><Field label="複查者"><Input value={r.settings.reviewer} maxLength={100} onChange={e=>reviewer(e.target.value)}/></Field><Field label="教練備註／下次驗證"><Textarea value={r.notes} maxLength={10000} rows={4} placeholder="一次改一項：觀察、教練判斷、練習內容、下次相同條件重拍。" onChange={e=>notes(e.target.value)}/></Field></div><div className="print-only"><p>複查者：{r.settings.reviewer||"未填寫"}</p><p style={{whiteSpace:"pre-wrap"}}>{r.notes}</p></div>
 <footer className="report-foot">{r.file.name} · {r.engine} · 儲存版本 {r.version}<br/>SHA256：{r.file.sha256||"未取得"}<br/>AI訓練篩查不取代當場競走裁判。170°／165°是未校準工程提示，並非官方判罰門檻。</footer></article>;
}
export function GuidePanel(){return <section className="guide-grid"><article className="card"><Camera className="guide-icon"/><h2>第一輪先建立無痛基準</h2><p>先拍Easy側面，再依症狀與教練判斷拍Race側面、正面及後面。髖部不適時不做Fast測試，也不追PB。</p><ol><li><strong>固定手機，鏡頭垂直行進方向。</strong>全身及鞋底完整入鏡，光線充足，不追拍，不開人像虛化。</li><li><strong>側面先拍近側清楚的那條腿。</strong>換方向補拍另一側；鏡像影片需先還原左右。</li><li><strong>保留原檔。</strong>建議1080p、60fps以上；120／240fps可改善慢動作定位，但仍須核對檔案時間。</li><li><strong>目標每側6–10個清楚的步態週期。</strong>可分多次通過鏡頭累積。單側接地到同側下次接地才是一個stride。</li></ol></article>
 <article className="card"><Footprints className="guide-icon"/><h2>點線如何幫你看動作？</h2><div className="guide-sequence"><p><b>01</b> 匯入影片，先偵測畫面人物，再點選或圈選一位選手。</p><p><b>02</b> 開始追蹤分析；框隨目標移動，藍色左、橘色右。</p><p><b>03</b> 點候選事件，看原片鞋底並調整時間。</p><p><b>04</b> 確認IC及Vertical，檢查兩者之間的伸膝。</p><p><b>05</b> 開啟參考線、匯出PNG，與教練討論單一改動。</p></div><p>圈選起點請挑選全身與軀幹清楚的畫面。腿部跳點或局部遮擋時，該側暫停取值，框仍依清楚的軀幹移動；重新確認連續穩定點位後才恢復量測。無法確認同一人時持續掃描影片、暫停量測；連續三格重新確認原目標後自動恢復，不需因短暫遮擋重新圈選。搜尋區間保留空白，不跨缺口計算步態。長時間離開畫面或有多個相似目標時，仍可能無法自動確認身分。「重新圈選・新片段」保留原紀錄並另建分析。要追蹤至某一幀，系統也會從起點重新確認並保留整段缺值；已有分析時另存紀錄。已追蹤幀可人工修正髖、膝、踝。衣著相近的密集人群仍須人工回看確認，追蹤不保證身分辨識正確率。</p></article>
 <article className="card"><h2>不同畫面，回答不同問題</h2><div className="table-scroll"><table><thead><tr><th>鏡位</th><th>本版可觀察</th><th>不宜推論</th></tr></thead><tbody><tr><td>側面</td><td>近側膝角、接地窗口、接觸候選、軀幹投影</td><td>遠側精確膝角、鞋底壓力</td></tr><tr><td>正／後面</td><td>左右髖高度差的二維投影、軀幹偏移</td><td>真實三維髖旋轉、疼痛原因</td></tr></tbody></table></div><p className="helper">綠色地面線是人工參考。未校準長度時，本版不輸出公分步幅、骨盆位移或左右總分。</p></article>
 <article className="card"><h2>規則、量測與資料</h2><p>正常速度的肉眼可見性與慢動作分析分開。AI候選不是犯規判決；系統不會由1–2格離地直接給紅牌。</p><p>影片在你的瀏覽器分析。按儲存會保存骨架、事件、症狀及報告；「備份原片」才會另外上傳影片，方便跨裝置重看。可匯出JSON並刪除紀錄。</p><p>JSON包含身體動作與症狀資料，交給教練時請自行決定分享範圍。</p><p><a href="https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker" target="_blank" rel="noreferrer">MediaPipe Pose官方說明 ↗</a></p><p><a href="https://worldathletics.org/news/series/race-walking-technique-rules-straight-leg" target="_blank" rel="noreferrer">World Athletics競走伸膝說明 ↗</a></p></article></section>;}
